### ISSUE TITLE
stan_input_helpers.R -- line 431

### ISSUE THREAD

**Issue by KaiyueZou** [HopkinsIDD/cholera-mapping-pipeline#261]
https://github.com/HopkinsIDD/cholera-mapping-pipeline/blame/dev_staninput_refactor/packages/taxdat/R/stan_input_helpers.R#L431

I am not sure if this is a bug; maybe I just don't understand it well. I wonder when we try to connect an isolated grid cell, why do we only try to connect it to the grid cells above it in the `sf_grid` object, instead of connecting it to all the unisolated cells? Here's my suggestion as to what it could be changed to: 

```
dist_to_main <- sf::st_distance(
        smooth_grid_it[vertex, ], 
        smooth_grid_it[seq_len(nrow(smooth_grid_it))[seq_len(nrow(smooth_grid_it)) != isolated_vertices], ]
      ) %>% 
        as.vector()
```

**Comment by eclee25** [comment]
Isolated grid cells should only be connected to its nearest neighbors in the sf_grid.

**Comment by javierps** [comment]
This is a good question, I suppose this was because of the top-left ordering which assumes cells are always connected to things before it. But I don't see why it could not be the case that things after it are closest.

I am not sure if there are isolated vertices in the UGA run for which I had done the adjacency figure.

@KaiyueZou do you think you could try looking into cases where connections do occur, and compare the current version and your proposed solution?

Let me know if you don't have time and I will try to take a look.

**Comment by KaiyueZou** [comment]
Got it, I can take a look!
